### ISSUE TITLE
Modal Pop Ups for Components

### ISSUE THREAD

**Issue by ayojackay** [Merits-App/merits#42]
Creating Modals for:

- Sign up
- Profile's Components

**Comment by benreckas** [comment]
Everyone just needs to include Jacque's code in their components. We'll leave it open until it's on everyone's component.

**Comment by ayojackay** [comment]
Converting the MODALS to the components individually

**Comment by ayojackay** [comment]
#17 #19 issues are to be included

**Comment by ayojackay** [comment]
@dramirez2096 @shaala  ***IMPORTANT***
